const all = {
  en: {
    maplestory: 'MapleStory',
    design: 'Design',
    understand: 'I understand',
    isCashFilter: 'Is Cash',
    genderFilter: 'Gender Filter',
    male: 'Male',
    female: 'Female',
    quickView: 'Quick View',
    removeAll: 'Remove All',
    prototype: 'This project is actively being developed and considered a prototype.',
    alpha: 'Public Alpha',
    unofficialNotice: 'The unofficial MapleStory simulator and designer.',
    properties: 'Properties',
    expression: 'Facial Expression',
    action: 'Pose / Action',
    skin: 'Skin',
    zoom: 'Zoom',
    universal: 'Universal',
    pet: 'Pet',
    character: 'Character',
    name: 'Name',
    illiumEars: 'Illium Ears',
    mercEars: 'Mercedes Ears',
    frame: 'Frame',
    animate: 'Animate',
    addBgToGif: 'Add BG to GIF',
    visible: 'Visible',
    flipHorizontal: 'Flip Horizontal',
    footholdSnapping: 'Foothold Snapping',
    lock: 'Lock',
    downloadSpriteSheet: 'Download Spritesheet',
    willDownloadZip: 'Will download a .zip',
    downloadLayeredSpriteSheet: 'Download Layered Spritesheet',
    requiresPDNPlugin: 'Requires PDN Plugin',
    deleteCharacter: 'Delete Character',
    petType: 'Pet Type',
    deletePet: 'Delete Pet',
    accessory: "Accessory",
    badge: "Badge",
    belt: "Belt",
    earrings: "Earrings",
    emblem: "Emblem",
    faceAccessory: "Face Accessory",
    medal: "Medal",
    eyeDecoration: "Eye Decoration",
    earring: "Earring",
    ring: "Ring",
    pendant: "Pendant",
    pocketItem: "Pocket Item",
    powerSource: "Power Source",
    shoulderAccessory: "Shoulder Accessory",
    totem: "Totem",
    armor: "Armor",
    hat: "Hat",
    cape: "Cape",
    top: "Top",
    glove: "Glove",
    overall: "Overall",
    bottom: "Bottom",
    shield: "Shield",
    shoes: "Shoes",
    testArmor: "Test Armor",
    other: "Other",
    android: "Android",
    dragonEquipment: "Dragon Equipment",
    mechanicalHeart: "Mechanical Heart",
    mechanicEquipment: "Mechanic Equipment",
    petEquipment: "Pet Equipment",
    bits: "Bits",
    shovel: "Shovel",
    pickaxe: "Pickaxe",
    skillEffect: "Skill Effect",
    petUse: "Pet Use",
    oneHandedWeapon: "One-Handed Weapon",
    scepter: "Scepter",
    oneHandedAxe: "One-Handed Axe",
    katara: "Katara",
    cane: "Cane",
    dagger: "Dagger",
    desperado: "Desperado",
    whipBlade: "Whip Blade",
    oneHandedBluntWeapon: "One-Handed Blunt Weapon",
    shiningRod: "Shining Rod",
    soulShooter: "Soul Shooter",
    staff: "Staff",
    oneHandedSword: "One-Handed Sword",
    wand: "Wand",
    testWeapon: "Test Weapon",
    cash: "Cash",
    psyLimiter: "Psy-limiter",
    chain: "Chain",
    gauntlet: "Gauntlet",
    secondaryWeapon: "Secondary Weapon",
    ballast: "Ballast",
    magicMarble: "Magic Marble",
    spellbook: "Spellbook",
    arrowFletching: "Arrow Fletching",
    powderKeg: "Powder Keg",
    farSight: "Far Sight",
    card: "Card",
    ironChain: "Iron Chain",
    bowThimble: "Bow Thimble",
    jewel: "Jewel",
    document: "Document",
    magicArrow: "Magic Arrow",
    charm: "Charm",
    orb: "Orb",
    rosary: "Rosary",
    daggerScabbard: "Dagger Scabbard",
    wristBand: "Wrist Band",
    arrowhead: "Arrowhead",
    jettSCore: "Jett's Core",
    novaSEssence: "Nova's Essence",
    soulRing: "Soul Ring",
    magnum: "Magnum",
    kodachi: "Kodachi",
    whistle: "Whistle",
    jettFists: "Jett Fists",
    mass: "Mass",
    foxMarble: "Fox Marble",
    coreController: "Core Controller",
    charges: "Charges",
    chessPiece: "Chess Piece",
    transmitter: "Transmitter",
    wings: "Wings",
    twoHandedWeapon: "Two-Handed Weapon",
    twoHandedAxe: "Two-Handed Axe",
    bow: "Bow",
    crossbow: "Crossbow",
    dualBowgun: "Dual Bowgun",
    gun: "Gun",
    handCannon: "Hand Cannon",
    knuckle: "Knuckle",
    twoHandedBlunt: "Two-Handed Blunt",
    poleArm: "Pole Arm",
    spear: "Spear",
    twoHandedSword: "Two-Handed Sword",
    claw: "Claw",
    katana: "Katana",
    fan: "Fan",
    lapis: "Lapis",
    lazuli: "Lazuli",
    armCannon: "Arm Cannon",
    character: "Character",
    face: "Face",
    hair: "Hair",
    monster: "Monster",
    crusaderCodex: "Crusader Codex",
    monsterBattle: "Monster Battle",
    mount: "Mount",
    consumable: "Consumable",
    potion: "Potion",
    foodAndDrink: "Food and Drink",
    statusCure: "Status Cure",
    petFood: "Pet Food",
    transformation: "Transformation",
    eXPPotion: "EXP Potion",
    characterModification: "Character Modification",
    timeSaver: "Time Saver",
    equipmentBox: "Equipment Box",
    teleportItem: "Teleport Item",
    eXPBuff: "EXP Buff",
    appearance: "Appearance",
    armorScroll: "Armor Scroll",
    helmet: "Helmet",
    eye: "Eye",
    topwear: "Topwear",
    bottomwear: "Bottomwear",
    gloves: "Gloves",
    belts: "Belts",
    shoulder: "Shoulder",
    equipment: "Equipment",
    pet: "Pet",
    weaponScroll: "Weapon Scroll",
    oneHandedBW: "One-Handed BW",
    twoHandedBW: "Two-Handed BW",
    polearm: "Polearm",
    zero: "Zero",
    specialScroll: "Special Scroll",
    cleanSlateScroll: "Clean Slate Scroll",
    slotCarver: "Slot Carver",
    bonusPotentialScroll: "Bonus Potential Scroll",
    chaosScroll: "Chaos Scroll",
    equipEnhancement: "Equip Enhancement",
    potentialScroll: "Potential Scroll",
    awakeningStamp: "Awakening Stamp",
    innocenceScroll: "Innocence Scroll",
    fusionAnvil: "Fusion Anvil",
    whiteScroll: "White Scroll",
    hammer: "Hammer",
    magnifyingGlass: "Magnifying Glass",
    timeExtension: "Time Extension",
    luckyDayScroll: "Lucky Day Scroll",
    protectionScroll: "Protection Scroll",
    safetyScroll: "Safety Scroll",
    guardianScroll: "Guardian Scroll",
    equipmentChange: "Equipment Change",
    soulWeapon: "Soul Weapon",
    miracleCube: "Miracle Cube",
    trade: "Trade",
    masteryBook: "Mastery Book",
    aPSPReset: "AP/SP Reset",
    monsterTaming: "Monster Taming",
    circulator: "Circulator",
    dust: "Dust",
    tablet: "Tablet",
    projectile: "Projectile",
    arrow: "Arrow",
    thrown: "Thrown",
    crossbowBolt: "Crossbow Bolt",
    bullet: "Bullet",
    monsterFamiliar: "Monster/Familiar",
    monsterCard: "Monster Card",
    familiarSkill: "Familiar Skill",
    familiarCard: "Familiar Card",
    recipe: "Recipe",
    smithingRecipe: "Smithing Recipe",
    accessoryCraftingRecipe: "Accessory Crafting Recipe",
    alchemyRecipe: "Alchemy Recipe",
    synergyMachine: "Synergy Machine",
    megaphone: "Megaphone",
    summoningSack: "Summoning Sack",
    message: "Message",
    lieDetector: "Lie Detector",
    wedding: "Wedding",
    owl: "Owl",
    capsule: "Capsule",
    itemPot: "Item Pot",
    monsterDrop: "Monster Drop",
    questItem: "Quest Item",
    cosmetic: "Cosmetic",
    minigame: "Minigame",
    petCommand: "Pet Command",
    book: "Book",
    effect: "Effect",
    coin: "Coin",
    container: "Container",
    eXPTicket: "EXP Ticket",
    eventItem: "Event Item",
    cashShop: "Cash Shop",
    rewardItem: "Reward Item",
    potentialLock: "Potential Lock",
    fusion: "Fusion",
    coupon: "Coupon",
    crafting: "Crafting",
    mineralOre: "Mineral Ore",
    mineralProcessed: "Mineral Processed",
    rareOre: "Rare Ore",
    rareProcessedOre: "Rare Processed Ore",
    craftingItem: "Crafting Item",
    herb: "Herb",
    herbOil: "Herb Oil",
    maker: "Maker",
    chair: "Chair",
    extractor: "Extractor",
    title: "Title",
    decoration: "Decoration",
    key: "Key",
    commerci: "Commerci",
    tradeGood: "Trade Good",
    shipEnhancement: "Ship Enhancement",
    evolutionLab: "Evolution Lab",
    core: "Core",
    mission: "Mission",
    nebulite: "Nebulite",
    rankDNebulite: "Rank D Nebulite",
    rankCNebulite: "Rank C Nebulite",
    rankBNebulite: "Rank B Nebulite",
    rankANebulite: "Rank A Nebulite",
    rankSNebulite: "Rank S Nebulite",
    teleportRock: "Teleport Rock",
    package: "Package",
    itemStore: "Item Store",
    questHelper: "Quest Helper",
    randomReward: "Random Reward",
    specialItem: "Special Item",
    gachapon: "Gachapon",
    surpriseBox: "Surprise Box",
    exchangeCoupon: "Exchange Coupon",
    equipmentModification: "Equipment Modification",
    scroll: "Scroll",
    upgradeSlot: "Upgrade Slot",
    sPAPModification: "SP/AP Modification",
    protection: "Protection",
    eXPCoupon: "EXP Coupon",
    dropCoupon: "Drop Coupon",
    entryPass: "Entry Pass",
    inventorySlot: "Inventory Slot",
    eXPCoupons: "EXP Coupons",
    skillModification: "Skill Modification",
    weapon: "Weapon",
    hairCoupon: "Hair Coupon",
    hairColorCoupon: "Hair Color Coupon",
    faceCoupon: "Face Coupon",
    cosmeticLens: "Cosmetic Lens",
    skinCoupon: "Skin Coupon",
    ear: "Ear",
    facialExpression: "Facial Expression",
    special: "Special",
    petAppearance: "Pet Appearance",
    freeMarket: "Free Market",
    hiredMerchant: "Hired Merchant",
    storePermit: "Store Permit",
    auctionHouse: "Auction House",
    messengerAndSocial: "Messenger and Social",
    weatherEffect: "Weather Effect",
    messenger: "Messenger",
    kite: "Kite",
    note: "Note",
    song: "Song",
    characterEffect: "Character Effect",
    guildForumEmoticon: "Guild Forum Emoticon",
    messageboard: "Messageboard",
    miscellaneous: "Miscellaneous",
    cakeVsPie: "Cake vs Pie",
    language: 'Language',
    playMusic: 'Play Music'
  },
  br: {
    maplestory: 'MapleStory',
    design: 'Design',
    understand: 'Eu Concordo',
    isCashFilter: 'Apenas Cash',
    genderFilter: 'Filtro de Gênero',
    male: 'Masculino',
    female: 'Feminino',
    quickView: 'Visualização Rápida',
    removeAll: 'Remover Todos',
    prototype: 'Este projeto está sendo constantemente desenvolvido e é considerado um protótipo.',
    alpha: 'Alpha Público',
    unofficialNotice: 'O simulador e designer não-oficial de Maplestory.',
    properties: 'Propriedades',
    expression: 'Expressão Facial',
    action: 'Pose / Ação',
    skin: 'Pele',
    zoom: 'Zoom',
    universal: 'Universal',
    pet: 'Mascote',
    character: 'Personagem',
    name: 'Nome',
    illiumEars: 'Orelhas de Illium',
    mercEars: 'Orelhas de Mercedes',
    frame: 'Quadro',
    animate: 'Animar',
    addBgToGif: 'Adicionar fundo ao GIF',
    visible: 'Visível',
    flipHorizontal: 'Virar Horizontalmente',
    footholdSnapping: 'Apoiar pés automáticamente',
    lock: 'Trancar',
    downloadSpriteSheet: 'Baixar Spritesheet',
    willDownloadZip: 'Será baixado um .zip',
    downloadLayeredSpriteSheet: 'Baixar Spritesheet dividida por Camadas',
    requiresPDNPlugin: 'Requer  do Plugin PDN',
    deleteCharacter: 'Deletar Personagem',
    petType: 'Tipo de Mascote',
    deletePet: 'Deletar Mascote',
    accessory: "Acessório",
    badge: "Insígnia",
    belt: "Cinto",
    earrings: "Brincos",
    emblem: "Emblema",
    faceAccessory: "Accessório de Face",
    medal: "Medalha",
    eyeDecoration: "Decoração de Olho",
    earring: "Brinco",
    ring: "Anel",
    pendant: "Pingente",
    pocketItem: "Item de Bolso",
    powerSource: "Fonte de Energia",
    shoulderAccessory: "Ombreira",
    totem: "Totem",
    armor: "Armadura",
    hat: "Chapéu",
    cape: "Capa",
    top: "Camisa",
    glove: "Luva",
    overall: "Macacão",
    bottom: "Calça",
    shield: "Escudo",
    shoes: "Sapatos",
    testArmor: "Armadura de Teste",
    other: "Outro",
    android: "Androide",
    dragonEquipment: "Equipamento de Dragão",
    mechanicalHeart: "Coração Mecânico",
    mechanicEquipment: "Equipamento de Mecânico",
    petEquipment: "Equipmento de Mascote",
    bits: "Bits",
    shovel: "Pá",
    pickaxe: "Picareta",
    skillEffect: "Efeito de Habilidade",
    petUse: "Item de Mascote",
    oneHandedWeapon: "Arma de uma Mão",
    scepter: "Cetro",
    oneHandedAxe: "Machado de uma Mão",
    katara: "Katara",
    cane: "Bengala",
    dagger: "Adaga",
    desperado: "Desperado",
    whipBlade: "Espada-Chicote",
    oneHandedBluntWeapon: "Porrete de uma Mão",
    shiningRod: "Cajado Brilhante",
    soulShooter: "Soul Shooter",
    staff: "Bastão",
    oneHandedSword: "Espada de uma Mão",
    wand: "Varinha",
    testWeapon: "Arma de Teste",
    cash: "Cash",
    psyLimiter: "Limitador Psíquico",
    chain: "Corrente",
    gauntlet: "Manopla",
    secondaryWeapon: "Arma Secundária",
    ballast: "Lastro",
    magicMarble: "Berlinde Mágico",
    spellbook: "Livro de Feitiços",
    arrowFletching: "Penas de Flecha",
    powderKeg: "Barril de Pó",
    farSight: "Visão Distante",
    card: "Carta",
    ironChain: "Corrente de Ferro",
    bowThimble: "Luvas para Arco",
    jewel: "Jóia",
    document: "Documento",
    magicArrow: "Flecha Mágica",
    charm: "Amuleto",
    orb: "Orbe",
    rosary: "Rosário",
    daggerScabbard: "Bainha de Adaga",
    wristBand: "Pulseira",
    arrowhead: "Ponta de Flecha",
    jettSCore: "Núcleo de Jett",
    novaSEssence: "Essência dos Nova",
    soulRing: "Anel das Almas",
    magnum: "Munição Magnum",
    kodachi: "Kodachi",
    whistle: "Apito",
    jettFists: "Punhos do Jett",
    mass: "Distintivo",
    foxMarble: "Berlinde de Raposa",
    coreController: "Núcleo Controlador",
    charges: "Cargas",
    chessPiece: "Peça de Xadrez",
    transmitter: "Transmissor",
    wings: "Asas",
    twoHandedWeapon: "Arma de duas Mãos",
    twoHandedAxe: "Machado de duas Mãos",
    bow: "Arco",
    crossbow: "Besta",
    dualBowgun: "Bestas Duplas",
    gun: "Arma de Fogo",
    handCannon: "Canhão de Mão",
    knuckle: "Luvas de Batalha",
    twoHandedBlunt: "Porrete de duas Mãos",
    poleArm: "Arma de Haste",
    spear: "Lança",
    twoHandedSword: "Espada de duas Mãos",
    claw: "Garra",
    katana: "Katana",
    fan: "Leque",
    lapis: "Lapis",
    lazuli: "Lazuli",
    armCannon: "Canhão de Braço",
    character: "Personagem",
    face: "Face",
    hair: "Cabelo",
    monster: "Monstro",
    crusaderCodex: "Códex do Cavaleiro",
    monsterBattle: "Batalha de Monstros",
    mount: "Montaria",
    consumable: "Consumível",
    potion: "Poção",
    foodAndDrink: "Comida e Bebida",
    statusCure: "Cura de Status",
    petFood: "Comida de Mascote",
    transformation: "Transformação",
    eXPPotion: "Poção de EXP",
    characterModification: "Modificação de Personagem",
    timeSaver: "Economizador de Tempo",
    equipmentBox: "Caixa de Equipamento",
    teleportItem: "Item de Teleporte",
    eXPBuff: "Buff de EXP",
    appearance: "Aparência",
    armorScroll: "Pergaminho de Armadura",
    helmet: "Capacete",
    eye: "Olho",
    topwear: "Camisa",
    bottomwear: "Calça",
    gloves: "Luvas",
    belts: "Cintos",
    shoulder: "Ombreira",
    equipment: "Equipamento",
    pet: "Mascote",
    weaponScroll: "Pergaminho de Arma",
    oneHandedBW: "AdH de uma Mão",
    twoHandedBW: "AdH de duas Mãos",
    polearm: "Arma de Haste",
    zero: "Zero",
    specialScroll: "Pergaminho Especial",
    cleanSlateScroll: "Pergaminho de Limpeza",
    slotCarver: "Escultor de Encaixe",
    bonusPotentialScroll: "Pergaminho de Potencial Bônus",
    chaosScroll: "Pergaminho do Caos",
    equipEnhancement: "Melhora de Equipamento",
    potentialScroll: "Pergaminho de Potencial",
    awakeningStamp: "Selo do Despertar",
    innocenceScroll: "Pergaminho da Inocência",
    fusionAnvil: "Bigorna de Fusão",
    whiteScroll: "Pergaminho Branco",
    hammer: "Martelo",
    magnifyingGlass: "Lupa",
    timeExtension: "Extensão de Tempo",
    luckyDayScroll: "Pergaminho do dia de Sorte",
    protectionScroll: "Pergaminho de Proteção",
    safetyScroll: "Pergaminho de Segurança",
    guardianScroll: "Pergaminho Guardião",
    equipmentChange: "Troca de Equipamento",
    soulWeapon: "Arma das Almas",
    miracleCube: "Cubo Milagroso",
    trade: "Troca",
    masteryBook: "Livro de Mastria",
    aPSPReset: "Reiniciar AP/SP",
    monsterTaming: "Domesticação de Monstro",
    circulator: "Circulador",
    dust: "Pó",
    tablet: "Tablete",
    projectile: "Projétil",
    arrow: "Flecha",
    thrown: "Arremessado",
    crossbowBolt: "Tiro de Besta",
    bullet: "Bala",
    monsterFamiliar: "Monstro/Familiar",
    monsterCard: "Carta de Monstro",
    familiarSkill: "Habilidade do Familiar",
    familiarCard: "Carta de Familiar",
    recipe: "Receita",
    smithingRecipe: "Fórmula de Metalurgia",
    accessoryCraftingRecipe: "Receita de Confecção de Acessório",
    alchemyRecipe: "Fórmula de Alquimia",
    synergyMachine: "Máquina de Sinergia",
    megaphone: "Megafone",
    summoningSack: "Saco de Invocação",
    message: "Mensagem",
    lieDetector: "Detector de Mentiras",
    wedding: "Casamento",
    owl: "Coruja",
    capsule: "Capsula",
    itemPot: "Pote de Item",
    monsterDrop: "Drop de Monstro",
    questItem: "Item de Quest",
    cosmetic: "Cosmético",
    minigame: "Minigame",
    petCommand: "Comando de Mascote",
    book: "Livro",
    effect: "Efeito",
    coin: "Moeda",
    container: "Recipiente",
    eXPTicket: "Ticket de EXP",
    eventItem: "Item de Evento",
    cashShop: "Loja de Cash",
    rewardItem: "Item Premium",
    potentialLock: "Travar Potencial",
    fusion: "Fusão",
    coupon: "Cupom",
    crafting: "Confecção",
    mineralOre: "Minério",
    mineralProcessed: "Minério Processado",
    rareOre: "Minério Raro",
    rareProcessedOre: "Minério Raro Processado",
    craftingItem: "Item de Confecção",
    herb: "Erva",
    herbOil: "Óleo de Erva",
    maker: "Fabricante",
    chair: "Cadeira",
    extractor: "Extrator",
    title: "Título",
    decoration: "Decoração",
    key: "Chave",
    commerci: "Commerci",
    tradeGood: "Trocar Bens",
    shipEnhancement: "Melhoramento de Navio",
    evolutionLab: "Laboratório da Evolução",
    core: "Núcleo",
    mission: "Missão",
    nebulite: "Nebulite",
    rankDNebulite: "Nebulite tipo D",
    rankCNebulite: "Nebulite tipo C",
    rankBNebulite: "Nebulite tipo B",
    rankANebulite: "Nebulite tipo A",
    rankSNebulite: "Nebulite tipo S",
    teleportRock: "Pedra de Teleporte",
    package: "Pacote",
    itemStore: "Loja de Itens",
    questHelper: "Auxiliar de Quests",
    randomReward: "Recompensa Aleatória",
    specialItem: "Item Especial",
    gachapon: "Gachapon",
    surpriseBox: "Caixa Surpresa",
    exchangeCoupon: "Cupom de Troca",
    equipmentModification: "Modificação de Equipamento",
    scroll: "Pergaminho",
    upgradeSlot: "Melhorar Encaixe",
    sPAPModification: "Modificação de SP/AP",
    protection: "Proteção",
    eXPCoupon: "Cupom de EXP",
    dropCoupon: "Cupom de Drop",
    entryPass: "Passe de Entrada",
    inventorySlot: "Encaixe de Inventário",
    eXPCoupons: "Cupons de EXP",
    skillModification: "Modificação de Habilidade",
    weapon: "Arma",
    hairCoupon: "Cupom de Cabelo",
    hairColorCoupon: "Cupom de cor de Cabelo",
    faceCoupon: "Cupom de Face",
    cosmeticLens: "Lentes Cosméticas",
    skinCoupon: "Cupom de Pele",
    ear: "Orelha",
    facialExpression: "Expressão Facial",
    special: "Especial",
    petAppearance: "Aparência de Mascote",
    freeMarket: "Mercado Livre",
    hiredMerchant: "Mercador Contratado",
    storePermit: "Autorização de Loja",
    auctionHouse: "Casa de Leilão",
    messengerAndSocial: "Mensageiro e Social",
    weatherEffect: "Efeito Climático",
    messenger: "Mensageiro",
    kite: "Pipa",
    note: "Nota",
    song: "Música",
    characterEffect: "Efeito de Personagem",
    guildForumEmoticon: "Emoticom de Fórum de Guilda",
    messageboard: "Quadro de Mensagens",
    miscellaneous: "Diversos",
    cakeVsPie: "Bolo vs Torta",
    language: 'Idioma',
    playMusic: 'Tocar Música'
  },
  nl: {
    language: 'Taal',
    playMusic: 'Speel Muziek',
    pet: 'Diertje',
    skin: 'Huid',
    design: 'Ontwerp',
    understand: 'Ik begrijp het',
    genderFilter: 'Geslacht Filter',
    male: 'Man',
    female: 'Vrouw',
    quickView: 'Snel Overzicht',
    removeAll: 'Verwijder Alles',
    prototype: 'Dit project is actief in ontwikkeling en wordt beschouwd als prototype.',
    alpha: 'Openbare Alfa',
    unofficialNotice: 'De onofficiële MapleStory simulator en ontwerper.',
    properties: 'Eigenschappen',
    expression: 'Gezichtsuitdrukkingen',
    action: 'Pose / Actie',
    skin: 'Huid',
    universal: 'Universeel',
    character: 'Personage',
    name: 'Naam',
    illiumEars: 'Illium Oren',
    mercEars: 'Mercedes Oren',
    animate: 'Animeer',
    addBgToGif: 'Voeg achtergrond toe aan GIF',
    visible: 'Zichtbaar',
    flipHorizontal: 'Horizontaal Omdraaien',
    footholdSnapping: 'Foothold Snappen',
    lock: 'Slot',
    willDownloadZip: 'Zal een .zip downloaden',
    downloadLayeredSpriteSheet: 'Download Gelaagde Spritesheet',
    requiresPDNPlugin: 'Vereist PDN Plugin',
    deleteCharacter: 'Verwijder Personage',
    petType: 'Type Diertje',
    deletePet: 'Verwijder Diertje',
    accessory: "Accessoire",
    belt: "Riem",
    earrings: "Oorbellen",
    emblem: "Embleem",
    faceAccessory: "Gezicht Accessoire",
    medal: "Medaille",
    eyeDecoration: "Oog Decoratie",
    earring: "Oorbel",
    pendant: "Hanger",
    pocketItem: "Zak-Item",
    powerSource: "Energiebron",
    shoulderAccessory: "Schouder Accessoire",
    armor: "Harnas",
    hat: "Hoed",
    top: "Bovenste",
    glove: "Handschoen",
    bottom: "Onderste",
    shield: "Schild",
    shoes: "Schoenen",
    testArmor: "Test Harnas",
    other: "Anders",
    dragonEquipment: "Draak Uitrusting",
    mechanicalHeart: "Mechanisch Hart"
  },
  jp: {
    maplestory: 'メイプルストーリー',
    design: 'デザイン',
    understand: 'わかります',
    isCashFilter: 'キャッシュショップの商品のみ',
    genderFilter: '性別',
    male: '男性',
    female: '女性',
    quickView: '早見',
    removeAll: 'すべて削除',
    prototype: 'このプロジェクトは積極的に開発され、試作品とみなされています。',
    alpha: 'アルファバージョン',
    unofficialNotice: '非公式のム メイプルストーリーシミュレータ',
    properties: '特性',
    expression: '表情',
    action: 'ポーズ',
    skin: '肌の色',
    zoom: 'ズームレンズ'
  },
  kr: {
    maplestory: '메이플 스토리',
    design: '디자인',
    understand: '이해 했어',
    isCashFilter: '캐시 샵 상품 만',
    gender: '성별',
    male: '남성',
    female: '여자',
    quickView: '퀵뷰',
    removeAll: '모두 제거',
    prototype: '이 프로젝트는 활발히 개발되고 프로토 타입으로 간주됩니다.',
    alpha: '알파 버전',
    unofficialNotice: '비공식 메이플 스토리 시뮬레이터 및 디자이너.',
    properties: '특성',
    expression: '표정',
    action: '자세',
    skin: '피부색',
    zoom: '줌'
  },
  ch: {
    maplestory: '楓之谷',
    design: '設計',
    understand: '我知道了!',
    isCashFilter: '現金道具',
    genderFilter: '性別設定',
    male: '男性',
    female: '女性',
    quickView: '道具清單',
    removeAll: '移除全部',
    prototype: '此計畫目前正在積極開發和考慮原型中.',
    alpha: '預覽版本',
    unofficialNotice: '非官方製作的楓之谷模擬器 / 設計.',
    properties: '屬性',
    expression: '表情',
    action: '姿勢 / 動作',
    skin: '皮膚',
    zoom: '放大',
    universal: '共用',
    pet: '寵物',
    character: '人物',
    name: '名字',
    illiumEars: '伊利恩耳朵',
    mercEars: '精靈耳朵',
    frame: '影格',
    animate: '動畫',
    addBgToGif: '儲存為GIF',
    visible: '顯示',
    flipHorizontal: '水平翻轉',
    footholdSnapping: '漂浮設定',
    lock: '鎖定',
    downloadSpriteSheet: '下載行走圖',
    willDownloadZip: '檔案為 .zip',
    downloadLayeredSpriteSheet: '下載行走圖圖層分解',
    requiresPDNPlugin: '需要PDN檔案',
    deleteCharacter: '刪除角色',
    petType: '寵物類型',
    deletePet: '刪除寵物',
    light: '光',
    ashen: '淺藍',
    palePink: '淡粉',
    tanned: '曬黑',
    pale: '蒼白',
    green: '綠色',
    ghostly: '鬼魅',
    dark: '黑暗',
    clay: '泥土',
    white: '白色',
    mercedes: '精靈'
  }
}

export default {
  getLocalized(language) {
    return {
      ...all['en'],
      ...all[language]
    }
  }
}
